apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    path: nginx-app
    repoURL: https://github.com/AmetDev/task26.git
    targetRevision: HEAD
    helm:
      releaseName: nginx-app
      values: |
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: testingargo.zapto.org
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: nginx-tls
              hosts:
                - testingargo.zapto.org
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 